project_id = "xvsgdzwadxbwpevdezbp"

[functions.admin-password-reset]
verify_jwt = false

[functions.sync-ghl-contact]
verify_jwt = false

[functions.get-ghl-conversations]
verify_jwt = false

[functions.decode-equipment]
verify_jwt = false

[functions.search-documentation]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.send-estimator-notification]
verify_jwt = false

[functions.verify-ghl-custom-fields]
verify_jwt = false

[functions.save-abandoned-cart]
verify_jwt = false

[functions.google-calendar-sync]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false


[functions.workedge-sync]
verify_jwt = false

[functions.workedge-webhook]
verify_jwt = false
